version: '3'
services:
    app:
        build: ./docker
        ports:
            - 80:80
        volumes:
            - .:/var/www/mapguesser
        links:
            - 'mariadb'
            - 'mail'
    mariadb:
        image: mariadb:10.1
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'mapguesser'
            MYSQL_USER: 'mapguesser'
            MYSQL_PASSWORD: 'mapguesser'
    mail:
        image: marcopas/docker-mailslurper:latest
        ports:
            - 8080:8080
            - 8085:8085
volumes:
    mysql:
